### ISSUE TITLE
How to know when transcription/audio save is complete

### ISSUE THREAD

**Issue by robertmadsen** [amazon-connect/amazon-connect-realtime-transcription#11]
We are doing some post processing on the transcripts and the audio file. Is there a way to know that the transcribe/save function has completed?

**Comment by robertmadsen** [comment]
Discovered the events for both AWS and DynamoDB and implemented Lambdas to handle.

**Comment by robertmadsen** [comment]
Reopened because setting an event for DynamoDB still doesn't give me the ability to know when the final transcript has been written. So, is there any way to get a signal or message or event that says that the amazon-connect-realtime-transcription lambda function has completed?

**Comment by efh365** [comment]
If you want a notification when the transcription is finished, you could modify the function to send a notification via SNS when the CompletableFuture from startStreamTranscription has completed. I believe that would solve your use case.
