### ISSUE TITLE
Dynamo and S3 stooped updating

### ISSUE THREAD

**Issue by damurphy3** [amazon-connect/amazon-connect-realtime-transcription#17]
Hi guys,
Wondering if you could help me. Set this up this morning and it was working perfectly, then all of a sudden it stopped updating on dynamo and on S3

No errors in the logfiles either, has anyone seen this happen before?

**Comment by efh365** [comment]
I have not seen that before. Do you see any errors in the console? Did you change any flags in the lambda function to disable transcription and audio storage?

**Comment by damurphy3** [comment]
No errors in the console, everything works just fine. Flags remain unchanged, both set to true. Doesn't appear to be a resource issue either, was just hoping you might have seen this before, we also opened a case with amazon to look into it.
