### ISSUE TITLE
Close Amazon Connect Stream

### ISSUE THREAD

**Issue by czhao028** [amazon-connect/amazon-connect-realtime-transcription#19]
Is there a way to do this within the code (triggering Connect Stream to close)? Within my contact flow, I need to pause streaming and I've tried 1. closing the input stream and 2. cancelling the subscription, though they don't work very well. Is there a more straightforward way to do this?

**Comment by czhao028** [comment]
For example, with a computer mic, you can simply do inputStream.close(). What's the respective function to stop Streaming through Kinesis (after you run client.startStreamTranscription())?

**Comment by efh365** [comment]
In order for you to stop the stream via the Lambda code instead of with the Stop Streaming block in the Contact Flow, you will need to stop the ExecutorService. The executor logic is in the KVSByteToAudioEventSubscription.java file.
