### ISSUE TITLE
Issue in getting wav files uploaded in S3

### ISSUE THREAD

**Issue by tejasb09** [amazon-connect/amazon-connect-realtime-transcription#20]
Hi,
I am unable to get the wav file upload to  S3 working. I don't see any exceptions in logs. The transcription  to dynamodb is working fine.

*I do see saveCallRecording=true in the logs for the transcriber lambda

Any advise?

Regards,

**Comment by efh365** [comment]
Hi,
Can you add more logs to help diagnose where you are seeing the issue? The section of code where the audio upload begins is in KVSTranscribeStreamingLambda.closeFileAndUploadRawAudio(). 

A few other comments/questions:
- Do you see the logs "Skipping upload to S3..."?
- In AudioUtils.uploadRawAudio() add a catch for all Exceptions and log there to see if an exception is being thrown
- Do you see the logs "Uploading Audio: to <bucket>/<key> from <wavefile>"?

Any additional logs that you do or do not see would be helpful for diagnosing this issue.

**Comment by tejasb09** [comment]
Hi,
Thanks for your response. I will add more logging to understand what might be wrong and post back.

Meanwhile, the only "error" I see is: Task timed out after 600.00 seconds

Also, I am not to clear on what should I be setting for:  INPUT_KEY_PREFIX

Regards,

**Comment by efh365** [comment]
If you are seeing that exception then something is blocking you from uploading audio to the bucket. I would check a few things:
1. Give your execution role "s3:*" permissions to see whether you are missing an S3 permission
2. Check your S3 bucket policy
3. Check the bucket name you are using and make sure it is the same as your bucket. Check the case sensitivity

**Comment by spawar1991** [comment]
HI @efh365 ,

I'm also facing an S3 Upload issue. As you mentioned above, it seems like all the things are proper in place at our end.

What could be the other possibility of not getting wav audio file in S3?

Best,
Swapnil Pawar
