### ISSUE TITLE
Stop media streaming block not working

### ISSUE THREAD

**Issue by bgomezatlas** [amazon-connect/amazon-connect-realtime-transcription#21]
I have a problem while trying to stop the media streaming because it seams that the streaming never ends until the call is finished. 

To put in context, I am developing a call center answered by a bot (using connect, lex, lambda, S3, kinesis, dynamo and transcribe) and I have different interactions with the user. For example, I start asking the user his name, then his phone number, then his address, etc.. This audios are stored in S3 using the lambda function for this project, that transcribes the content, stores the transcription in Dynamo and stores a .wav in S3.

For all those interactions, I start streaming before the user talks and I end it after he finish. Then I start again the streaming, ask the user whatever, wait for his response and end the streaming again. 

The problem is that in this example, the first audio never stops till I finish the call and, as it is still running, contains as well the answer for the second, third and all successive questions, making a huge file that only ends when the call is finished. The second audio contains the second answer as well as the third, fourth, etc.. The third audio will contain the third response, fourth, etc...

It seems that the problem is that the "Stop media streaming" block is not working and the streaming never ends.

**Comment by vgonisanz** [comment]
Same problem here. The "Stop media streaming" block do not trigger the eof, so the MKVParser wait up to 30s to this event to end the process. If the call ends before, the eof arrive and the parsers end earlier.

**Comment by bgomezatlas** [comment]
@vgonisanz I opened a support case in AWS like a couple of years ago and they answered me that there was an issue with the stop media streaming function and that they would solve it as soon as they could. I am not aware whether they have solve it or not, or even if they have started... I suppouse they haven't solve it because you are facing the same problem, but I've never received again any more messages from them.
Sorry for not being able to help you more.

**Comment by mcosicaws** [comment]
StopStreaming is an async function, and takes some time from the moment it has been invoked until the streaming stops. You could do a simple test by: 

1) StartStreaming
2) Provide some speech input
3) StopStreaming, but continue providing speech input for another minute
4) Disconnect the call
5) Playback the file
6) You would hear the speech input, but it should be shorter than the actual duration of the call
7) That would prove that Streaming stopped before the end of the call

In case you need a lot of 'short' streaming segments, the better approach is to StartStreaming once, and then only store Timestamps when you'd Start and Stop (using either Contact Attributes or a DynamoDB table). At the end of the call, you would implement a post-processing function, that would read from KVS, based on Timestamps you stored in Contact Attributes / DynamoDB.

When you want to configure ‘Live media streaming’ on Amazon Connect, you’d actually find that option under ‘Data storage’ section, and you can set ‘Data retention period’.
This means that Amazon Connect streams audio to KVS, but KVS keeps (‘stores’) the audio for the time specified in ‘Data retention period’.

For example, if your retention period was set to 24 hours, KVS would keep the streamed audio for 24 hours. 

You can read KVS in real-time, if that was needed, for instance, if you need to transcribe the call in real-time, provide the customer sentiment in real-time etc.
But, reading KVS in real-time is not mandatory. You can read it any time, over and over again, as long as you read it within the ‘Data retention period’.

For instance, if I wanted to record customer’s interaction with ‘IVR’ (Contact Flow, Lex), I could place Start Streaming block in the Contact Flow, let customer interact with Contact Flow/Lex, and at some point Stop Streaming, and then invoke a Lambda function passing Start Timestamp and Stop Timestamp, to read the stream. 

Even without invoking Stop Streaming, I could wait for CTR to be produced, and only then invoke a Lambda function to go and read from the KVS stream. 

I’m not completely familiar with your use-case, but you could:
- Start Streaming in your Contact Flow
- Let customer interact with the Contact Flow
- Set a custom attribute, like ‘SpeakNameStart’, to note the timestamp
- Place a Get Customer Input block, asking customer for their name
- Set another custom attribute, like ‘SpeakNameStop’, to note the timestamp
- Let customer continue with Contact Flow
- At the end, Stop Streaming and Disconnect

Once CTR is produced, you would get Start and Stop timestamps for the entire recording, and you’d invoke your Lambda function to read between these two markers - to get the entire recording.

But then additionally get SpeakNameStart and SpeakNameStop markers (timestamps) from the attributes, and invoke your Lambda function again to read KVS between these 2 markers.

As a result, you’d have 2 wav files, one with the entire recording, and the other one with the audio only between SpeakNameStart and SpeakNameStop markers (timestamps).

When reading from KVS, you’d first get fragments between the two timestamps, and then read the media from all the fragments. For that purpose, you'd use `AmazonKinesisVideoArchivedMedia` and:

```java
...
final ListFragmentsResult fragmentResult = amazonKinesisVideoArchivedFragment.listFragments(
                new ListFragmentsRequest()
                        .withFragmentSelector(new FragmentSelector().withFragmentSelectorType(FragmentSelectorType.SERVER_TIMESTAMP).withTimestampRange(new TimestampRange().withStartTimestamp(new Date(Long.parseLong(this.StartTimestamp))).withEndTimestamp(new Date(Long.parseLong(this.StopTimestamp)))))
                        .withStreamName(streamName)
        );
...
```

I hope this helps, on a high-level, but please let us know if you need any additional details.

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
