### ISSUE TITLE
No docs on Connect specific MKV tags

### ISSUE THREAD

**Issue by luclement** [amazon-connect/amazon-connect-realtime-transcription#22]
Where does the tag with the `ContactId` reside? Namely, in the example it checks if the `ContactId` from the MKV tags match the `connectContactId` from the KVS event:

https://github.com/aws-samples/amazon-connect-realtime-transcription/blob/b21f5baab582108d9d53775022fa93ae4e4351d3/src/main/java/com/amazonaws/kvstranscribestreaming/KVSUtils.java#L71

I wrote the KVS output to an MKV file, but only see the following tags:

```
|+ Tags
| + Tag
|  + Simple
|   + Name: AWS_KINESISVIDEO_FRAGMENT_NUMBER
|   + String: 91343852333181457156434608487321492997712000000
|  + Simple
|   + Name: AWS_KINESISVIDEO_SERVER_TIMESTAMP
|   + String: 1567100227.205
|  + Simple
|   + Name: AWS_KINESISVIDEO_PRODUCER_TIMESTAMP
|   + String: 1109909.253
```

I'm trying to create an MKV file manually that matches the output from Connect to KVS so that I can write some automation to simulate KVS events.

**Comment by efh365** [comment]
The ContactId resides on the FragmentMetadataVisitor.BasicMkvTagProcessor. You will need to print out the tags when the first MkvStartMasterElement is received because the tags are cleared after that point. I printed out the tags on line 70 and got the following tag names: ContactId, InstanceId, MimeType, and Events.

**Comment by luclement** [comment]
I guess my question is more along the lines of where do these tags reside within the EBML header within the MKV itself? Is there a way I can inject these tags into an MKV file that I've created myself? Using `mkvinfo` it seems like the only tags in the `Tags` block are the three above.

My understanding is that the `BasicMkvTagProcessor` looks at the `Tags` block in the EBML header?

**Comment by mcosicaws** [comment]
The ContactId tag is only present in the EBML MASTER element. 

In the KVSUtils.java file, the loop processing elements starts at line 94:
`while (streamingMkvReader.mightHaveNext()) {..}`

Line 102 checks if the current element is EBML
`if (MkvTypeInfos.EBML.equals(mkvElement.getElementMetaData().getTypeInfo())) {..}`

If that element was EBML, then line 103 checks if that is Master
`if (mkvElement instanceof MkvStartMasterElement) {...}`

If the element was Master, line 104 reads the tags:
`String contactIdFromStream = getContactIdFromStreamTag(tagProcessor);`

Method that reads tags, starts at line 67:

`    private static String getContactIdFromStreamTag(FragmentMetadataVisitor.BasicMkvTagProcessor tagProcessor) {
        Iterator iter = tagProcessor.getTags().iterator();
        while (iter.hasNext()) {
            MkvTag tag = (MkvTag) iter.next();
            if ("ContactId".equals(tag.getTagName())) {
                return tag.getTagValue();
            }
        }
        return null;
    }`

**MkvTypeInfos:** 
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/ebml/MkvTypeInfos.java

`public static final EBMLTypeInfo EBML = new EBMLTypeInfo.EBMLTypeInfoBuilder().name("EBML").id(0x1A45DFA3).level(0).type(EBMLTypeInfo.TYPE.MASTER).build();`

based on the specification here:
https://github.com/Matroska-Org/foundation-source/blob/master/spectool/specdata.xml

**Comment by luclement** [comment]
Appreciate the detailed follow up. Was able to figure this out, but hopefully this will be useful for others. Closing.
