### ISSUE TITLE
Failed to create "initContactDetails" as S3 can't be found

### ISSUE THREAD

**Issue by scarai-sap** [amazon-connect/amazon-connect-realtime-transcription#26]
Hi Expert,

As docs said, I tried to create stack in cloud foundry, then met issue as below. May you give me some idea what's wrong about my configuration?

![image](https://user-images.githubusercontent.com/38693320/68272312-3f984d00-009e-11ea-9881-9ea40aa044ef.png)

The parameters I set as below, I only need write down the existingS3BucketName and existingS3Path, right?

![image](https://user-images.githubusercontent.com/38693320/68272363-69517400-009e-11ea-9691-f52c6eb6c1ea.png)

**Comment by scarai-sap** [comment]
looks you have to change the s3BucketName with a new one

**Comment by lokendra9009** [comment]
Hi, I am facing the same issue, How were you able to resolve it. Can you quote an example of exisitingS3Path. I think I am entering a wrong path.

**Comment by scarai-sap** [comment]
How I resolved? I just write anyone instead of the default one. Maybe you what's in your way is another issue?

**Comment by lokendra9009** [comment]
The issue seems quite same to me PFB the screenshot below 

https://user-images.githubusercontent.com/6012837/74427540-4db7ef80-4e7d-11ea-96bd-004c55ec39e5.png
