### ISSUE TITLE
Not getting full transcription for a call

### ISSUE THREAD

**Issue by madmaxgorgon** [amazon-connect/amazon-connect-realtime-transcription#29]
Hi Team,
I have created a contact flow and invoked kvs-trigger function. 
But in the dynamo DB table I am not getting full transcription for the call.
For example, I have conversation like below,

IVR Bot: Hello how may I help you?
Customer: show my balance
IVR Bot: what is your account number?
Customer: 123
IVR Bot: responds with correct answers
Customer: list my accounts
IVR Bot: responds with the answer
and so on...

But I can only see show my balance and 123 in my dynamoDB table which means it does not store the transcript for whole call.

Please help me with this urgently.

**Comment by efh365** [comment]
Hi @madmaxgorgon. There are a few things you need to check here. 
1) Have you deployed the latest code that handles streaming and transcribing both calls? You should have 2 DDB tables if so - one for audio to the customer and one for audio from the customer.
2) Does the start streaming block in the contact flow stream audio in both directions?
3) Have you set the contact attribute telling the lambda function to stream in both directions?
