### ISSUE TITLE
Error deploying code

### ISSUE THREAD

**Issue by angel7170** [amazon-connect/amazon-connect-realtime-transcription#30]
Hi, I am new to AWS but this should be a silly question for you. When I tried to create a stack, I get the attached error. How do I resolve this? 

The S3 bucket I created is "deployment" 

Please assist. Thanks

![image](https://user-images.githubusercontent.com/58609234/70353921-6d5ae800-183c-11ea-8c86-ff00797e99c3.png)

**Comment by efh365** [comment]
Hi @angel7170 . You need to make sure you are deploying the stack for the region you are in. It looks like you are in eu-central-1 but are trying to deploy the stack from us-east-1
