### ISSUE TITLE
Change nodejs8.10 to nodejs12.x as nodejs8.10 is no longer supported.

### ISSUE THREAD

**Issue by imankurpatel000** [amazon-connect/amazon-connect-realtime-transcription#32]
Currently, the cloudformation.template file has nodejs8.10 which is no longer supported for creating or updating AWS Lambda functions.

https://github.com/amazon-connect/amazon-connect-realtime-transcription/blob/67fe50fd19beba9b9607ffcfd035bcf294616427/deployment/cloudformation.template#L615

**Comment by zackrspv** [comment]
I did a full replacement in the cloudformation.template to replace nodejs8.0 to nodejs12.x and i didn't get the error.  But, sadly, the whole system refuses to create. No matter what I try, I cannot get this cloudformation template to actually DO the build.

**Comment by Ra100NZ** [comment]
@zackrspv I had the same issue. It was coming from the last item in cloudformation.template (custom type triggering create_contact_flow). I removed it and tried to create new stack again. It was created successfully.

Then you can copy the JSON of sample flow from create_contact_flow (variable mainFlow, value is starting with {"id....) and import it to AWS Connect. Once it is created, you just need to select names of lambda functions that are triggered from AWS Connect flow manually.

**Comment by efh365** [comment]
Thanks for the heads up. I will update this project to use node 12

**Comment by zackrspv** [comment]
> @zackrspv I had the same issue. It was coming from the last item in cloudformation.template (custom type triggering create_contact_flow). I removed it and tried to create new stack again. It was created successfully.
> 
> Then you can copy the JSON of sample flow from create_contact_flow (variable mainFlow, value is starting with {"id....) and import it to AWS Connect. Once it is created, you just need to select names of lambda functions that are triggered from AWS Connect flow manually.

Hey there Ra100NZ :) Thanks for that, i'll give it a try. Do you happen to have a copy of that template?

Thanks!

**Comment by efh365** [comment]
I just updated the solution to NodeJS 12.x
