### ISSUE TITLE
Error in lambda functions module uuid not found

### ISSUE THREAD

**Issue by imankurpatel000** [amazon-connect/amazon-connect-realtime-transcription#33]
3 of the lambda functions for node.js uses uuid but the uuid not included as a node_modules in the zip. I know how to fix it but I thought may be it should be added by default so someone following the instructions step by step does not encounter an issue.

**Comment by efh365** [comment]
Thanks for the heads up. I'll make a fix

**Comment by efh365** [comment]
I just updated the solution so this should not longer be an issue
