### ISSUE TITLE
Stack creation fails with error Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. 

### ISSUE THREAD

**Issue by lokendra9009** [amazon-connect/amazon-connect-realtime-transcription#35]
The following error occurs when I try to create the stack by following the steps mentioned in readme.md

Logical ID : processContactSummary

Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 69bd456e-6c18-4af8-b54f-a2a26ce0a5c0)

![image](https://user-images.githubusercontent.com/6012837/74427540-4db7ef80-4e7d-11ea-96bd-004c55ec39e5.png)

**Comment by efh365** [comment]
Thanks for bringing this to my attention. What region are you in?

**Comment by lokendra9009** [comment]
region=us-east-1
N. Virginia

**Comment by efh365** [comment]
Oh wait sorry I was thinking this was the other solution where we provide the stack creation link. So if the object cannot be found then there are a few possibilities:

1) you have a misconfiguration with your parameters and are pointing to the wrong S3 location
2) you have not uploaded the necessary zip file
3) you have uploaded the file in the wrong location
4) your s3 bucket is homed in a different region than where you are deploying the stack

Please make sure you are following the directions precisely as said in the README.

**Comment by lokendra9009** [comment]
I have create an S3 bucket and then created a folder with name "deployment" and then uploaded all the files present inside this project's deployment folder there.

The region of S3 bucket is same i.e. us-east-1 and the deployment stack too has the same region.
 
Can we jump on a call ?

**Comment by lokendra9009** [comment]
Closing this issue, there was as configuration error that I was making.

**Comment by alauer67** [comment]
Hi @lokendra9009 I am getting the same error, what was your configuration error and how did you resolve it?
