### ISSUE TITLE
Increasing Lambda limit for recording length

### ISSUE THREAD

**Issue by philManWithBeard** [amazon-connect/amazon-connect-realtime-transcription#36]
Hi there, 
I need to increase the Lambda limit for a recording from the 15 minutes stated in your documentation to potentially 3 hours. I can see that the Lambda timeout can't be extended over 15 minutes though. Is there a way of sending a regular wake up to stop it timing out?
Kind regards
Phil

**Comment by efh365** [comment]
Hi Phil,
If you need the limit to last longer than 15 minutes you will need to use an EC2 instance or Fargate. Lambda cannot run longer than 15 minutes.
