### ISSUE TITLE
Get Amazon Transcribe in connect widget (Contact Control Panel?)?

### ISSUE THREAD

**Issue by SachinKaura** [amazon-connect/amazon-connect-realtime-transcription#37]
Hello,

I would like to know the process how can I call transcribe from Contact Control Panel? 
If possible can you please explain the options available? 

Thanks,
SK

**Comment by taylor-zr** [comment]
Hello SK,

You can do this by using a Streams API Custom CCP and pulling the transcript segments!

**Comment by efh365** [comment]
Hi SK,

As Taylor-zr suggested, you can create an embedded CCP and use the Streams API to call Transcribe. You can see an example of how this is done in this GitHub repo: https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/
