### ISSUE TITLE
Not accurate transcribe result Audio to Text in Real time.

### ISSUE THREAD

**Issue by vdineshmca** [amazon-connect/amazon-connect-realtime-transcription#39]
Hi There,

Anyone please help me. Do you also find the differences if use Real Time Transcribe in Amazon Connect.
 
I'm sharing my experiences here, found the difference with Real time transcribe and conversation recording wav file manually upload using transcribe service. Good result in manually convert wav file to text.

First Way - Without Agent:
----------------------------
I'm trying to achieve the Voicemail functionality in case of no agents during non working hours. Customer dialing the contact center then we prompt to leave your message then customer leave voice for 30 secs then it will call the transcribe stream lambda to proceed the conversion of audio to text in Dynamo DB but receiving difference sentences in the output.

Second Way - With Agent:
----------------------------

The same way we transferred the call to dummy agent ccp to retrieve the .wav file. Now, customer recording is available in the s3 bucket and copy the file path then enter it in the transcribe service to create job then getting accurate audio to text.

1. Anyone help me why there is the difference in Real time transcribe and manually convert .wav file.
2. Accurate result receiving in the manual convert .wav file. Why?
3. Any customized configuration available in Real time transcribe to receive the accurate response.
4. For one call at least three segments then how can we get all results in one final output in Dynamo table.
5. Without agent we have to achieve this functionality. Can anyone share your experience and documentation if available.

If you need any other details kindly let me know. 

Thanks for your help in advance.

Regards,
Dinesh Babu V

**Comment by efh365** [comment]
Hi Dinesh, 

Can you run an additional test for me? Can you pass the .wav file through transcribe streaming and let me know what the results are there? Transcribe and Transcribe Streaming make certain tradeoffs between accuracy and latency, but the results should still be pretty similar across a set of samples.

#3 - you can add a custom dictionary to the transcribe streaming that could help with some of the transcriptions.
#4 - After the call is completed you could invoke a Lambda function that then pulls all the items with the same contact id and merges it into one entry in a new table
