### ISSUE TITLE
Update version for transcribestreaming with new supported language

### ISSUE THREAD

**Issue by fjaviermoradiaz** [amazon-connect/amazon-connect-realtime-transcription#40]
New version available:

// https://mvnrepository.com/artifact/software.amazon.awssdk/transcribestreaming
compile group: 'software.amazon.awssdk', name: 'transcribestreaming', version: '2.13.39'

**Comment by dfw100** [comment]
I am closing the issue as transcribestreaming in build file is already upgraded to version [2.16.30](https://github.com/amazon-connect/amazon-connect-realtime-transcription/blob/219ca65b172957430a1e4a5b1c21f5bef6806e5d/build.gradle#L16) . Feel free to reopen to continue the discussion of anything else comes up with more details.
