### ISSUE TITLE
Amazon Transcribe Streaming service request in PHP or Laravel?

### ISSUE THREAD

**Issue by lucenarenato** [amazon-connect/amazon-connect-realtime-transcription#41]
# PHP - REAL TIME TRANSCRIPTION (StartStreamTranscription)
> Amazon Transcribe Streaming service request in PHP or Laravel?
I'm a PHP developer, I would like to use transcribe real time transcriptions, but I haven't found documentation for PHP about this tool, do you have a strength? 
https://stackoverflow.com/questions/62685811/amazon-transcribe-streaming-service-request-in-php-or-laravel

**Comment by efh365** [comment]
Hi, can you please clarify your question?

**Comment by lucenarenato** [comment]
> Olá, você pode esclarecer sua dúvida?

Hi, I need to make a connection to php with transcribeStreaming, but I haven't found any practical examples. I was informed that with websocket it is possible. If you have an example or some documentation that can help, I appreciate it.

**Comment by efh365** [comment]
Sorry, I am not aware of any examples of transcribe streaming with PHP. There could be something out there, but I am not familiar with PHP and I focus on Amazon Connect.
