### ISSUE TITLE
Not able to re trigger failed transcriptions

### ISSUE THREAD

**Issue by altesean** [amazon-connect/amazon-connect-realtime-transcription#42]
We are seeing occasional failures (believe to be service limit related, case opened) in the transcription that causes it to enter a error loop and never even try to copy the audio file to S3. When we try to re trigger the transcription from the same Lambda it goes straight to 'Completable future is complete.' in the logs then 'Skipping upload to S3. saveCallRecording was disabled or audio file has 0 bytes:' .   We have a identical lambda deployed under a different name and when we run it there it works as expected.

![image](https://user-images.githubusercontent.com/44910522/87490913-7995f780-c60c-11ea-8c32-3848a7e3ad13.png)

**Comment by dfw100** [comment]
Hi @altesean , is your support case resolved? The message 'Skipping upload to S3. saveCallRecording was disabled or audio file has 0 bytes:' is logged when either the contact attribute 'saveCallRecording' is set to false in the contact flow or when there is no audio available.

**Comment by dfw100** [comment]
Hi altesean, Please try the above solution and reopen the issue to continue the discussion if issue still exists.
