### ISSUE TITLE
Need to know all Service Quota restrictions. 

### ISSUE THREAD

**Issue by altesean** [amazon-connect/amazon-connect-realtime-transcription#43]
We are seeing failures of the transcription service once the number of concurrent calls exceeds 5, resulting in the following error.  
java.util.concurrent.CompletionException: software.amazon.awssdk.services.transcribestreaming.model.BadRequestException: Your request timed out because no new audio was received for 15 seconds. (Service: transcribe, Status Code: 400,

Others listed this as a capacity issue and closed it, however when we opened a ticket to increase the for 'Amazon Transcribe -The maximum number of concurrent streaming transcription jobs.' however support is saying that this is already set to 500.   What other service quotas effect this?

**Comment by efh365** [comment]
Hi,

The error seems to be due to there being no audio on one of the channels for 15 seconds. The transcription service will stop streaming if there is silence for 15 seconds. Can you confirm that this is happening only when you have 5 concurrent calls at once instead of when there is silence?
