### ISSUE TITLE
Live transcription stops after 5 mins

### ISSUE THREAD

**Issue by rpaulojade** [amazon-connect/amazon-connect-realtime-transcription#44]
Hi,

I am currently working on live transcription mostly based on this repository and we have been having an error that stops the live transcription after 5 mins. This is the error that gets thrown:

`software.amazon.awssdk.services.transcribestreaming.model.BadRequestException: Signature expired: 20200720T093804Z is now earlier than 20200720T093804Z (20200720T094304Z - 5 min.) (Service: transcribe, Status Code: 400, Request ID: 9207a474-b32d-4a29-a06c-6c9381075aa7)`

**Comment by rpaulojade** [comment]
Any response is really really appreciated.

**Comment by rpaulojade** [comment]
The thing we did is that of instead of saving the live transcription on the dynamodb we instead send the transcripted audio to an SNS topic that then gets taken by a lambda and sends it to the front end where a copy is then also saved in the dyamodb.

**Comment by efh365** [comment]
It looks like this is an issue with the streaming sdk. And update to the version should fix the issue for you. We will work on updating this repo as well. https://github.com/aws-samples/aws-transcribe-streaming-example-java/issues/12

**Comment by rpaulojade** [comment]
Hi updating from the repo worked. Do we have a specifici idea on why the error occured?

**Comment by boopathikumar018** [comment]
update the SDK version to 'software.amazon.awssdk:transcribestreaming:2.7.27' to fix the issue
