### ISSUE TITLE
Suggestion: Add clarification on the instructions of CoudFormation building process

### ISSUE THREAD

**Issue by Fercho120** [amazon-connect/amazon-connect-realtime-transcription#47]
Hi while trying to build the CloudFormation template I got an error creating the audio s3 bucket, I got this

![image](https://user-images.githubusercontent.com/18184315/92399693-53fb0b00-f0f0-11ea-854c-0d7e5b91a67f.png)

Apparently it was because I didn't change the default Audio bucket name, get solved after changing it, don't know why.

I suggest clarifying that you must personalize the Audio bucket name as I spended a few hours realizing where my error was (I'm quite a beningner with AWS)

**Comment by efh365** [comment]
Thanks for the suggestion! we will try to make that more obvious
