### ISSUE TITLE
Unable to deploy the CloudFormation Stack

### ISSUE THREAD

**Issue by shubhdevf** [amazon-connect/amazon-connect-realtime-transcription#48]
While trying to deploy the stack, I am getting the following error:

The following resource types are not supported for resource import: AWS::Lambda::Permission,AWS::Lambda::Permission,AWS::IAM::Policy,Custom::CreateKVSContactFlow,AWS::Lambda::Permission

Am I doing something wrong? Those resource types are indeed not listed at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html?icmpid=docs_cfn_console

**Comment by shubhdevf** [comment]
![image](https://user-images.githubusercontent.com/16588710/96602485-b01c9600-1310-11eb-8e7f-7c4343c83e59.png)

**Comment by mcosicaws** [comment]
When you open CloudFormation Console, and click on "Create stack", please make sure you have selected "With new resources (standard)", rather than "With existing resources (import resources)".

**Comment by mcosicaws** [comment]
Please re-open if needed
