### ISSUE TITLE
Is it possible to not send the transcribed result to ddb and use it for another api call in lambda instead?

### ISSUE THREAD

**Issue by jamesirvin188** [amazon-connect/amazon-connect-realtime-transcription#49]
Would like to use the transcript from the customer calling to send to an api call outside. Is is possible to edit the java function there? Thank you.

**Comment by efh365** [comment]
Hi James. Yes, you can do this. You have a few options:
1) If you dont want to store the transcript in DDB, you can replace the writes to DDB with another endpoint of your choosing. https://github.com/amazon-connect/amazon-connect-realtime-transcription/blob/master/src/main/java/com/amazonaws/kvstranscribestreaming/TranscribedSegmentWriter.java#L58 
2) You can use the websocket that is connected to the DDB and hook into it and write to a separate API from there
3) If you want to wait until the call is over, you could add a trigger on the S3 bucket that takes the CTR and send the full transcript to a separate API then.
