### ISSUE TITLE
IVR Interaction not recorded

### ISSUE THREAD

**Issue by ahartoch** [amazon-connect/amazon-connect-realtime-transcription#50]
Deat team,

 I have deployed the project however I'm not able to understand why the IVR interaction is not transcribed. I have created a very simple lex bot to recognize ok/accept input to be GDPR compliant, however, the spoken information for the voice bot is not recorded.  I would like to understand what am I doing wrong.

Kind Regards,
Alex

**Comment by efh365** [comment]
Hi Alex. Do you use the start streaming block before the Lex interaction? Are you not able to hear the customer or the Lex bot?

**Comment by wangning08115** [comment]
I have the same Question.  
Now i can record Agent and Consumer Voice, But the Lex voice can not be recored.
I use this project to deploy.

Below Picture:  The "Get customer input" block will speak some text.  But the voice can not be recored.
![image](https://user-images.githubusercontent.com/3455705/105659422-ae600100-5f03-11eb-8a7e-bba3217b036f.png)

**Comment by efh365** [comment]
@wangning08115 can you confirm that you have an environment variable in your lambda function that is "START_SELECTOR_TYPE" = "FRAGMENT_NUMBER" ?

ref: https://github.com/amazon-connect/amazon-connect-realtime-transcription#lambda-environment-variables

**Comment by efh365** [comment]
@wangning08115 did that fix your issue?

**Comment by dfw100** [comment]
Hi @wangning08115, I am closing the issue as it has been inactive for 21 days. Feel free to reopen to continue the discussion of anything else comes up.
