### ISSUE TITLE
"ExpiresAfter"  attribute set to milliseconds but Dynamo Db TTL says it only accepts only in seconds

### ISSUE THREAD

**Issue by kggunka** [amazon-connect/amazon-connect-realtime-transcription#51]
Hey,

Just want to get clarification on the part of the code line 103 in the function TranscribedSegmentWriter.java where the value is set in milliseconds for the attribute "ExpiresAfter" but in the Dynamo TTL documentation it says that the attribute has to be in seconds [1] thus records are not deleted after 7 days. Why is this the case or this is an issue with the code logic?

Thanks 

References:

[1] https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-before-you-start.html

**Comment by efh365** [comment]
Hi, good catch. I believe that was an oversight. We will update the code to reflect this change.

**Comment by dfw100** [comment]
Hi kggunka, I am closing the issue since the issue has been addressed in #57. Feel free to open a new ticket if anything else comes up.
