### ISSUE TITLE
How to call AWS comprehend services realtime?

### ISSUE THREAD

**Issue by wangning08115** [amazon-connect/amazon-connect-realtime-transcription#53]
How to call comprehend service realtime?
When this project transcription audio and save text to dynamodb, Can i call AWS comprehend services realtime? And save the comprehend  result to dynamodb realtime?
How can  i do ?
I need help.
@efh365   Thanks.

**Comment by efh365** [comment]
@wangning08115 please take a look at the parent solution: https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect

In that solution there is a trigger from DynamoDB to Lambda that then calls API Gateway to send realtime transcription to a websocket that then calls Comprehend from the frontend. You can follow that pattern and instead call Comprehend from a Lambda function you invoke based on a DynamoDB trigger if you dont have a frontend component.

**Comment by efh365** [comment]
@wangning08115 did you figure it out?

**Comment by dfw100** [comment]
Hi @wangning08115, I am closing the issue as it has been inactive for 21 days. Feel free to reopen to continue the discussion of anything else comes up.
