### ISSUE TITLE
Version of trancribestreaming sdk is not updated. It generates errors about added language

### ISSUE THREAD

**Issue by nuatmochoi** [amazon-connect/amazon-connect-realtime-transcription#55]
https://github.com/amazon-connect/amazon-connect-realtime-transcription/blob/0d0abe7c50a819561ca94b12cf4a3c63de298351/build.gradle#L11

The newest version is 2.16.10.
 
2.5.0 version generates many errors related added languages (ex> japanese, korean etc..) 

At the end of troubleshooting about language problem, I got to know version is not updated.

I hope other people don't encounter mistake like me, So correct this ASAP..

**Comment by tomohisaota** [comment]
I'm facing the same issue.
Here is the quick fix to make it work. 
I have updated the lib to 2.16.21, and force Java 8 as runtime.
Java 8 may not be necessary if you're not using Lambda.

build.gradle
```
apply plugin: 'java'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(dir: 'jars', include: '*.jar')
    compile group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.2'
    compile(
            'software.amazon.awssdk:transcribestreaming:2.16.21',

            'com.amazonaws:aws-java-sdk-dynamodb:1.11.475',
            'com.amazonaws:aws-java-sdk-kinesisvideo:1.11.475',
            'com.amazonaws:aws-lambda-java-core:1.2.0',
            'com.amazonaws:aws-lambda-java-events:1.2.0',
            'com.amazonaws:aws-java-sdk-cloudwatch:1.11.480',
            'org.slf4j:slf4j-api:1.7.24',
            'org.slf4j:slf4j-log4j12:1.7.24',

            // need this for our async clients
            'software.amazon.awssdk:netty-nio-client:2.2.0',

            // need this for logging
            'org.apache.commons:commons-lang3:3.6'
    )
}

task buildZip(type: Zip) {
    from compileJava
    from processResources

    into('lib') {
        from configurations.compileClasspath
    }
}

build.dependsOn buildZip

```

**Comment by efh365** [comment]
I just made this update and tested with it and it works. I will push a new version with this update shortly. @nuatmochoi can you confirm if this solved your problem?

**Comment by efh365** [comment]
Here is the pull request I created - can you check to see if this fixed your issue? https://github.com/amazon-connect/amazon-connect-realtime-transcription/pull/57

**Comment by nuatmochoi** [comment]
Thanks. It works well with #57.
