### ISSUE TITLE
How to make custom vocabulary & filter work?

### ISSUE THREAD

**Issue by IVRBuilder** [amazon-connect/amazon-connect-realtime-transcription#56]
Hi,
I'm new to AWS SDK and JAVA.

I'm trying to implement a vocabulary and vocabulary filter in Stream Transcription, but I’m having no luck with this:
Vocabularies or filters are not working in any transcript results.

problem:
The request object is created and startStreamTranscription succeeded, 
but there are not included in the response.

-------------------------------------------------------------- Code

private static final String TRANSCRIBE_VOCABULARY = System.getenv("TRANSCRIBE_VOCABULARY");
private static final String TRANSCRIBE_FILTER = System.getenv("TRANSCRIBE_FILTER");
private static final String TRANSCRIBE_FILTER_METHOD = System.getenv("TRANSCRIBE_FILTER_METHOD");

private static StartStreamTranscriptionRequest getRequest(Integer mediaSampleRateHertz, Optional <String> languageCode) {

        StartStreamTranscriptionRequest req =StartStreamTranscriptionRequest.builder()
                .mediaEncoding(MediaEncoding.PCM)
                .mediaSampleRateHertz(mediaSampleRateHertz)
                .languageCode(languageCode.isPresent() ? languageCode.get() : LanguageCode.EN_US.toString())
                .vocabularyName(TRANSCRIBE_VOCABULARY)
                .vocabularyFilterName(TRANSCRIBE_FILTER)
                .vocabularyFilterMethod(TRANSCRIBE_FILTER_METHOD)
//                .numberOfChannels(2)        //test
//                .showSpeakerLabel(true)
//                .enableChannelIdentification(true)
                .build();
        logger.info("StartStreamTranscriptionRequest=" + req);
        return req;

-------------------------------------------------------------- Request
StartStreamTranscriptionRequest(
	LanguageCode=ja-JP, 
	MediaSampleRateHertz=8000, 
	MediaEncoding=pcm, 
	VocabularyName=Vocab01, 
	VocabularyFilterName=Vocabfilter01, 
	VocabularyFilterMethod=Mask
)
 *Vocab01 and Vocabfilter01 exists on Transcribe console.

-------------------------------------------------------------- Response
StartStreamTranscriptionResponse(
	RequestId=6fdb8957-0846-47e7-ad00-xxxx,
	LanguageCode=ja-JP, 
	MediaSampleRateHertz=8000, 
	MediaEncoding=pcm, 
	SessionId=6cd60b6a-6e72-484d-8a24-xxxx, 
	ShowSpeakerLabel=false, 
	EnableChannelIdentification=false
)

-------------------------------------------------------------
The following are not included in response even if requested:
  VocabularyName
  VocabularyFilterName
  VocabularyFilterMethod
  .numberOfChannels
  (I don't know correct parameter name of this)

The response value is always "false" even if requested "true":
  ShowSpeakerLabel
  EnableChannelIdentification

--------------------------------------------------------------
I'm using software.amazon.awssdk:transcriptstreaming 2.6.12.
Region is ap-northeast-1.

What should I do?

**Comment by efh365** [comment]
@IVRBuilder, thanks for reaching out. Unfortunately we are not owners of the transcriptstreaming sdk and I haven't used the custom vocab feature before. From your request code, it looks like you are setting the vocab right. Are you sure that the StartStreamTranscriptionResponse will contain the vocab being used in the response when you print it out? Maybe it is being set but just isnt shown in the print statement. Through testing does it seem like the vocab filter is being used?

One thing I do notice is that you are using and env variable instead of the enum for the vocab mask. Can you update your code to use the enum instead? https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/transcribestreaming/model/VocabularyFilterMethod.html 

Could you try printing out ".getValueForField()" on the response object to see if the vocab is defined?

**Comment by IVRBuilder** [comment]
@efh365 , thank you for reply!

This problem has been resolved.
I'm sorry I didn't report it.

Further modifications were needed for the custom vocabulary and filters to work:
TranscribeStreamingRetryClient.java: rebuildRequestWithSession

-------------------------------------------code
private StartStreamTranscriptionRequest rebuildRequestWithSession(StartStreamTranscriptionRequest request) {


        StartStreamTranscriptionRequest.Builder build =StartStreamTranscriptionRequest.builder();

        build.mediaEncoding(request.mediaEncoding());
        build.mediaSampleRateHertz(request.mediaSampleRateHertz());
        build.languageCode(request.languageCode());
        if ( !StringUtils.isEmpty(request.vocabularyName()) && !request.vocabularyName().isEmpty() ){
            build.vocabularyName(request.vocabularyName());
        }
        if ( !StringUtils.isEmpty(request.vocabularyFilterName()) && !request.vocabularyFilterName().isEmpty() ) {
            build.vocabularyFilterName(request.vocabularyFilterName());
            build.vocabularyFilterMethod(request.vocabularyFilterMethod());
        }
        build.sessionId(UUID.randomUUID().toString());

        StartStreamTranscriptionRequest req = build.build();


/*        StartStreamTranscriptionRequest req =  StartStreamTranscriptionRequest.builder()
                .languageCode(request.languageCode())
                .mediaEncoding(request.mediaEncoding())
                .mediaSampleRateHertz(request.mediaSampleRateHertz())
                .vocabularyName(request.vocabularyName())
                .vocabularyFilterName(request.vocabularyFilterName())
                .vocabularyFilterMethod(request.vocabularyFilterMethod())
                .sessionId(UUID.randomUUID().toString())
                .build();
*/
        return req;
    }
-------------------------------------------
The custom vocabulary and filters are now working.

I am very grateful for this project.
Thank you very much!
