### ISSUE TITLE
Short Audio Messages Not Recorded

### ISSUE THREAD

**Issue by twagaman** [amazon-connect/amazon-connect-realtime-transcription#58]
I have noticed that short audio messages seem to have issues. If the message length is a few words (about 1-4 seconds), many times no audio is recorded at all. However, when the message is longer, 100% of the audio is captured.

**Comment by twagaman** [comment]
@efh365 Thank you for your response. My use case is actually using this to allow our callers to leave voice feedback about our IVR system, similar to a Voicemail. I'm only recording the caller side of the conversation, as there would be no input from the agent, as there is no agent. 

Should the caller leave a short message, then messages less than 4 seconds will be recorded with no audio. I believe this is actually an issue with Amazon Connect's Kinesis Video Stream Producer. In my humble opinion, making smaller fragments in the producer should correct this issue. This may actually be strictly an issue in base Connect functionality in how it creates the Kinesis Video Streams, and may actually be out of scope of this project.

**Comment by efh365** [comment]
I see, thanks for the explanation. Can you confirm that the START_SELECTOR_TYPE in the Lambda function that processes the KVS stream is set to FRAGMENT_NUMBER? If it is set to FRAGMENT_NUMBER then I will let the service team know about this limitation.

**Comment by dfw100** [comment]
Hi twagaman, could you please confirm that the START_SELECTOR_TYPE in the Lambda function that processes the KVS stream is set to FRAGMENT_NUMBER?

**Comment by khastation** [comment]
twagaman, please reopen if this issue persists.
