### ISSUE TITLE
Where is the jars folder?

### ISSUE THREAD

**Issue by psantora-amazon** [amazon-connect/amazon-connect-realtime-transcription#63]
Currently in the README it states:
Building the KVS Transcriber project
The lambda code is designed to be built with Gradle. All requisite dependencies are captured in the build.gradle file. The code also depends on the AWS Kinesis Video Streams Parser Library which has been built into a jar can be found in the jars folder. Simply use gradle build to build the zip that can be deployed as an AWS Lambda application. After running gradle build, the updated zip file can be found in the build/distributions folder

Ask is:
Where can I find the jars folder and jar file referred here? It's probably something obvious I'm missing :)

Thank you.

**Comment by khastation** [comment]
@psantora-amazon thanks for reaching out. You will find the jars AFTER you've built the project in your environment using `gradle build` in the `build/distributions/amazon-connect-realtime-transcription.zip` path. The zip file contains a `lib/` folder with all the jars related to the KVS parser library.
![image](https://user-images.githubusercontent.com/40148037/151293755-b7a8cac9-29c0-4811-9d2a-fc9189caa646.png)

Feel free to reopen if you continue seeing issues.
