### ISSUE TITLE
The solution contains kinesis parser which has log4js

### ISSUE THREAD

**Issue by fkhan439** [amazon-connect/amazon-connect-realtime-transcription#65]
Can you let us steps to secure the existing setup, help us to update the existing solution

**Comment by ranep210** [comment]
> Can you let us steps to secure the existing setup, help us to update the existing solution

We are facing same issue

**Comment by angieyu** [comment]
This has been addressed by PR https://github.com/amazon-connect/amazon-connect-realtime-transcription/pull/66

Please build and deploy the project again. Let us know how it goes.

**Comment by dfw100** [comment]
The source code is patched with the following versions of affected dependencies.

amazon-kinesis-video-streams-parser-library version to 1.1.0
org.slf4j:slf4j-api to 1.7.32
org.slf4j:slf4j-log4j12 to 1.7.32
