### ISSUE TITLE
Error while creating the stack

### ISSUE THREAD

**Issue by sdabidis** [amazon-connect/amazon-connect-realtime-transcription#67]
While creating the stack, I am getting the below error message:

Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 9d5037fd-8a9f-4c72-91ea-0a622b67bb0d; Proxy: null)

And it is failing all the process.
![voicemail](https://user-images.githubusercontent.com/94361498/151127410-405df5d0-f198-4453-9093-3d0e35033b84.png)

**Comment by AWilson10** [comment]
i have exact same issue. I raised a duplicate query prior to reading this.
Any resolution?

**Comment by khastation** [comment]
Hey @AWilson10 & @sdabidis,

Release v1.0.1 fixes the issue of missing *.zip files, thank you for your patience.
