### ISSUE TITLE
stack build error

### ISSUE THREAD

**Issue by AWilson10** [amazon-connect/amazon-connect-realtime-transcription#68]
Hello.
The error below trying to create the stack. Does the build expect zip files? as there are none in the repo.

Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code:

**Comment by khastation** [comment]
Hey @AWilson10,

Release v1.0.1 fixes the issue of missing *.zip files, thank you for your patience.
