### ISSUE TITLE
AWS Lambda end of support for Node.js 12

### ISSUE THREAD

**Issue by blink8512** [amazon-connect/amazon-connect-realtime-transcription#74]
AWS Lambda end of support for Node.js 12

We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.

We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.

End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Node.js 12. To find all such functions in your account, repeat this command for each region:

Can you all update this to work with Node.js 16?

**Comment by angieyu** [comment]
Hi, but we're looking into deprecating this solution. The technologies are no longer the one we would recommend. There is a built in API that would address these use cases better, see https://docs.aws.amazon.com/connect/latest/adminguide/contact-analysis-segment-streams.html
